# Generated by Django 5.0.4 on 2024-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
